name: Apply terraform
description: Apply terraform

inputs:
  path:
    description: "Path to Terraform root directory"
    required: false
    default: .

  plan_file:
    description: "Path to plan file. Will be relative to path if an absolute path is not specified"
    required: false
    default: "plan.out"


runs:
  using: composite

  steps:
    - name: Terraform apply
      shell: bash
      working-directory: ${{ inputs.path }}
      env:
        PLAN_FILE: ${{ inputs.plan_file }}
      run: |
        # 1. Run and send stdout to build log as usual
        terraform apply -auto-approve -input=false -no-color "$PLAN_FILE" \
          | tee output.txt

        # 2. Remove some github commands and fluff
        # This removes any line containing status updates on destruction or creation commands
        STDOUT="$(grep -v -E '(.*(Destroying|Creating|Modifying)\.\.\..*)|(.*(Destruction|Creation|Modifications) complete.*)' output.txt)"

        # Insert cleaned output back into output.txt
        echo "$STDOUT" > output.txt

        # 3. Write to step summary
        cat >> $GITHUB_STEP_SUMMARY <<EOF
        \`\`\`
        $STDOUT
        \`\`\`
        EOF

        # 4. Write output
        {
          echo 'stdout<<EOF'
          echo "$STDOUT"
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"

